USE dbms_assignment;

SET autocommit = 0;
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

START TRANSACTION;
SELECT * FROM PRODUCT;
#do anything here
DO SLEEP(10);
SELECT * FROM PRODUCT;
COMMIT;